const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
class El{constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.attributes={};this.className='';this.classList={add:()=>{},toggle:name=>{this.className=this.className.includes(name)?this.className.replace(name,'').trim():`${this.className} ${name}`.trim();return this.className.includes(name)}};this.textContent='';this.onclick=null}setAttribute(name,value){this.attributes[name]=String(value)}append(...items){this.children.push(...items)}replaceChildren(...items){this.children=[...items]}querySelectorAll(){return this.children.filter(x=>x!==this.children[0])}get firstElementChild(){return this.children[0]}click(){this.onclick?.()}set innerHTML(_){throw new Error('unsafe innerHTML')}}
const document={createElement:tag=>new El(tag),createTextNode:value=>({textContent:String(value)})};
const allText=node=>[node?.textContent||'',...(node?.children||[]).flatMap(allText)];
test('refresh preserves the active workflow and empty choices prevent submission',async()=>{
 const root=new El('root');let sent=0;
 const context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>true};context.globalThis=context;
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);
 const app=context.BdvmManagement.create(root,{snapshot:async()=>({version:1,actions:[{area:'industry',label:'Assign wagons',intentType:'test',fields:[{name:'assetIds',kind:'multiselect',options:[],required:true}]}]}),intent:async()=>{sent++;return{state:'Succeeded'}},exportLogs(){}});
 await app.refresh();root.children[0].children.find(x=>x.textContent==='Industry').click();await app.refresh();
 assert.equal(app.activeSection,'industry');assert.ok(allText(root).includes('No eligible option is currently available.'));
 const card=app.actionCard(app.snapshot.actions[0]);card.children.at(-1).click();assert.equal(sent,0);
});
test('technical identities are available in details rather than table columns',async()=>{
 const root=new El('root'),context={document,globalThis:null};context.globalThis=context;
 vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);
 const app=context.BdvmManagement.create(root,{snapshot:async()=>({companies:[{name:'Rail Company',leader:'You',technicalDetails:{companyId:'secret-id',version:3}}]}),exportLogs(){}});
 await app.refresh();const visible=allText(root);assert.ok(visible.includes('Technical details'));assert.ok(visible.some(value=>value.includes('secret-id')));assert.ok(!visible.includes('Technical Details'));
});
test('Management renders authoritative malicious text without HTML interpretation',async()=>{const root=new El('root'),transport={snapshot:async()=>({version:4,correlationId:'snapshot-1',companies:[{name:'<img src=x onerror=1>'}]}),intent:async()=>({state:'Succeeded'}),exportLogs(){}};const context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>true};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const app=context.BdvmManagement.create(root,transport);await app.refresh();assert.equal(app.snapshot.companies[0].name,'<img src=x onerror=1>');assert.match(app.status.textContent,/authoritative state snapshot-1/);assert.doesNotMatch(app.status.textContent,/authoritative state v4/)});
test('Management submits versioned bounded intent metadata and exposes reconciliation state',async()=>{const root=new El('root');let sent;const transport={snapshot:async()=>({version:7}),intent:async envelope=>(sent=envelope,{state:'Conflict',code:'version-conflict',correlationId:envelope.correlationId}),exportLogs(){}};const context={document,globalThis:null,crypto:{randomUUID:(()=>{let i=0;return()=>`uuid-${++i}`})()},confirm:()=>true};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const app=context.BdvmManagement.create(root,transport);await app.refresh();await app.submit('bdvm.management.wallet-transfer.v1',{amount:10});assert.equal(sent.moduleId,'BDVM.Management');assert.equal(sent.expectedVersion,7);assert.ok(sent.idempotencyKey);assert.equal(sent.payload.amount,10)});
test('destructive action confirmation can stop intent before transport',async()=>{const root=new El('root');let calls=0;const context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>false};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const app=context.BdvmManagement.create(root,{snapshot:async()=>({version:1}),intent:async()=>{calls++},exportLogs(){}});await app.refresh();await app.submit('bdvm.management.company-dissolve.v1',{}, {confirmation:'Dissolve?'});assert.equal(calls,0)});
test('frontend does not use HTML injection primitives or calculate balances and ownership',()=>{const source=fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8');assert.doesNotMatch(source,/\.innerHTML\s*=|insertAdjacentHTML|\beval\s*\(/);assert.doesNotMatch(source,/balance\s*[+\-*/]=|owner\s*=/i)});
test('action forms are collapsed until the user opens the needed operation',()=>{const source=fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),css=fs.readFileSync(path.join(__dirname,'..','Assets','app.css'),'utf8');assert.match(source,/aria-expanded/);assert.match(source,/classList\.toggle\('open'\)/);assert.match(css, /__action:not\(\.open\)>:not\(strong\)\{display:none\}/);assert.match(css,/flex-wrap:nowrap/)});
test('industry inputs, outputs and stocks remain visible as inert text',async()=>{const root=new El('root'),transport={snapshot:async()=>({version:1,industry:[{site:'Steel Mill',inputs:['Iron ore \\u00d7 2','Steel \\u2190 Harbor'],outputs:['Steel \\u00d7 1','Steel \\u2192 Machine Factory'],stocks:['Steel \\u2014 75 / 100']}]}),intent:async()=>({}),exportLogs(){}};const context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>true};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const app=context.BdvmManagement.create(root,transport);await app.refresh();const tabs=root.children[0];tabs.children.find(x=>x.textContent==='Industry').click();const visible=allText(root.children[root.children.length-1]);assert.ok(visible.includes('Steel Mill'));assert.ok(visible.includes('Iron ore \\u00d7 2'));assert.ok(visible.includes('Steel \\u2192 Machine Factory'));assert.ok(visible.includes('Steel \\u2014 75 / 100')) });
test('active management surfaces keep the focused navigation while deferred surfaces stay hidden',async()=>{const root=new El('root'),context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>true};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const app=context.BdvmManagement.create(root,{snapshot:async()=>({version:1}),intent:async()=>({}),exportLogs(){}});await app.refresh();const labels=root.children[0].children.map(x=>x.textContent);for(const expected of ['Companies','Wallets','Fleet','Catalog','Contracts','Industry','Diagnostics','Retry / reconcile','Export diagnostics'])assert.ok(labels.includes(expected));for(const hidden of ['Passengers','Leases','Deliveries','Assignments','Financing','Maintenance','Yard plans'])assert.ok(!labels.includes(hidden))});
test('Catalog keeps its actionable empty state',async()=>{const root=new El('root'),context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>true};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const app=context.BdvmManagement.create(root,{snapshot:async()=>({version:1,market:[]}),intent:async()=>({}),exportLogs(){}});await app.refresh();const tabs=root.children[0],panel=root.children[root.children.length-1];tabs.children[3].click();assert.match(panel.children[2].children[0].textContent,/No market offer exists yet/) });
test('complex surfaces explain their workflow and tabular data has visible column headings',async()=>{const root=new El('root'),context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>true};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const app=context.BdvmManagement.create(root,{snapshot:async()=>({version:1,diagnostics:[{subsystem:'World population',runtimeState:'Active'}]}),intent:async()=>({}),exportLogs(){}});await app.refresh();const tabs=root.children[0],panel=root.children[root.children.length-1];tabs.children.find(x=>x.textContent==='Industry').click();assert.match(panel.children[1].textContent,/Read-only warehouse directory/);tabs.children.find(x=>x.textContent==='Diagnostics').click();assert.match(panel.children[1].textContent,/Read-only health information/);const visible=allText(panel);assert.ok(visible.includes('Subsystem'));assert.ok(visible.includes('Runtime State'))});
test('browser-facing Management sources remain English-only',()=>{const sources=['app.js','app.css'].map(name=>fs.readFileSync(path.join(__dirname,'..','Assets',name),'utf8'));const french=/[àâçéèêëîïôùûüÿœ]|\b(?:actualiser|ouvrir|fermer|indisponible|itinéraire|trafic|joueur|compagnie|matériel|ferroviaire|déconnexion|connecté|hors ligne|rafraîchir|aucun|erreur|chargement|serveur|gare|voie|portefeuille|gestion|annuler|acheter|vendre|conducteur|affectation)\b/i;for(const source of sources)assert.doesNotMatch(source,french)});
test('schema-driven action forms submit typed values without browser-side business calculations',async()=>{const root=new El('root');let sent;const transport={snapshot:async()=>({version:9,actions:[{area:'fleet',label:'Rename vehicle',intentType:'bdvm.management.fleet.rename.v1',payload:{action:'fleet.rename',assetId:'a'},fields:[{name:'displayName',label:'Name',kind:'text',value:'Switcher',required:true}]}]}),intent:async envelope=>(sent=envelope,{state:'Succeeded'}),exportLogs(){}};const context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>true};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const app=context.BdvmManagement.create(root,transport);await app.refresh();root.children[0].children.find(x=>x.textContent==='Fleet').click();const panel=root.children[root.children.length-1],card=panel.children[4],button=card.children[card.children.length-1];button.click();await Promise.resolve();assert.equal(sent.payload.displayName,'Switcher');assert.equal(sent.payload.assetId,'a')});
test('host-provided compatible wagons are submitted from a multi-select without client filtering',async()=>{const root=new El('root');let sent;const transport={snapshot:async()=>({version:10,actions:[{area:'industry',label:'Assign compatible wagons',intentType:'bdvm.management.industry-manage.v1',payload:{action:'industry.manage',operation:'assign',contractId:'c1',forCompany:false},fields:[{name:'assetIds',label:'Compatible operator wagons',kind:'multiselect',required:true,options:['w1','w2']}]}]}),intent:async envelope=>(sent=envelope,{state:'Succeeded'}),exportLogs(){}};const context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>true};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const app=context.BdvmManagement.create(root,transport);await app.refresh();root.children[0].children.find(x=>x.textContent==='Industry').click();const panel=root.children[root.children.length-1],card=panel.children[4],select=card.children[1].children[1],button=card.children[card.children.length-1];select.children.forEach(item=>item.children[0].checked=true);button.click();await Promise.resolve();assert.deepEqual(Array.from(sent.payload.assetIds),['w1','w2']);assert.equal(sent.payload.forCompany,false);assert.equal(sent.payload.contractId,'c1')});
test('selects display human labels while submitting authoritative IDs',async()=>{const root=new El('root'),context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>true};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const app=context.BdvmManagement.create(root,{snapshot:async()=>({version:1,actions:[{area:'industry',label:'Configure company need',intentType:'bdvm.management.industry-manage.v1',payload:{},fields:[{name:'originId',label:'Pickup station',kind:'select',required:true,options:['SM'],optionLabels:{SM:'Steel Mill (ID: SM)'}}]}]}),intent:async()=>({state:'Succeeded'}),exportLogs(){}});await app.refresh();root.children[0].children.find(x=>x.textContent==='Industry').click();const panel=root.children[root.children.length-1],visible=allText(panel);assert.ok(visible.includes('Steel Mill (ID: SM)'))});
test('host refusal exposes its actionable reason instead of pretending to be offline',async()=>{const root=new El('root'),context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>true};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const app=context.BdvmManagement.create(root,{snapshot:async()=>({version:1}),intent:async()=>{throw new Error('Selected model is already configured.')},exportLogs(){}});await app.refresh();await app.submit('bdvm.management.intent.v1',{});assert.match(app.status.textContent,/Selected model is already configured/);assert.doesNotMatch(app.status.textContent,/Offline/)});
test('company governance actions are rendered from host descriptors',async()=>{const root=new El('root'),context={document,globalThis:null,crypto:{randomUUID:()=> 'uuid'},confirm:()=>true};context.globalThis=context;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..','Assets','app.js'),'utf8'),context);const actions=[{area:'companies',label:'Create a company',intentType:'bdvm.management.company-governance.v1',payload:{action:'company.create'},fields:[{name:'name',label:'Company name',kind:'text',required:true}]},{area:'companies',label:'Request to join Rail',intentType:'bdvm.management.company-governance.v1',payload:{action:'company.apply',companyId:'co'}}];const app=context.BdvmManagement.create(root,{snapshot:async()=>({version:1,companies:[],actions}),intent:async()=>({state:'Succeeded'}),exportLogs(){}});await app.refresh();const panel=root.children[root.children.length-1];assert.ok(allText(panel).includes('Create a company'));assert.ok(allText(panel).includes('Request to join Rail'))});
